/**
 * Verified scripture for the reflection companion.
 *
 * The model chooses a passage by REFERENCE ONLY. The text below is what the
 * site renders, so a misremembered verse is not possible: the worst the model
 * can do is pick a passage that fits poorly, never one that says something
 * scripture does not say.
 *
 * Berean Standard Bible, public domain. Generated by
 * scripts/build-scripture.py; do not edit by hand.
 *
 * Two passages carry an em dash inside the quotation (Isaiah 43:1-2 and
 * Psalm 127:1-2). That is the translation's own punctuation and is left alone;
 * we do not edit scripture to match a house style.
 */

export interface ScripturePassage {
  /** As a reader would cite it, e.g. "Philippians 4:6-7". */
  reference: string;
  /** Berean Standard Bible, verbatim. */
  text: string;
  /** What this passage speaks to, used by the model to choose. */
  themes: string[];
}

export const SCRIPTURE_LIBRARY: ScripturePassage[] = [
  {
    reference: "Philippians 4:6-7",
    text: "Be anxious for nothing, but in everything, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
    themes: ["anxiety", "fear", "overwhelm"],
  },
  {
    reference: "Isaiah 41:10",
    text: "Do not fear, for I am with you; do not be afraid, for I am your God. I will strengthen you; I will surely help you; I will uphold you with My right hand of righteousness.",
    themes: ["anxiety", "fear", "transition"],
  },
  {
    reference: "1 Peter 5:7",
    text: "Cast all your anxiety on Him, because He cares for you.",
    themes: ["anxiety", "burden"],
  },
  {
    reference: "Psalm 94:19",
    text: "When anxiety overwhelms me, Your consolation delights my soul.",
    themes: ["anxiety", "overwhelm"],
  },
  {
    reference: "Matthew 6:34",
    text: "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Today has enough trouble of its own.",
    themes: ["anxiety", "uncertainty"],
  },
  {
    reference: "Matthew 11:28-30",
    text: "Come to Me, all you who are weary and burdened, and I will give you rest. Take My yoke upon you and learn from Me; for I am gentle and humble in heart, and you will find rest for your souls. For My yoke is easy and My burden is light.",
    themes: ["exhaustion", "burden", "rest", "people-pleasing"],
  },
  {
    reference: "Psalm 55:22",
    text: "Cast your burden upon the LORD and He will sustain you; He will never let the righteous be shaken.",
    themes: ["burden", "exhaustion"],
  },
  {
    reference: "Isaiah 40:31",
    text: "But those who wait upon the LORD will renew their strength; they will mount up with wings like eagles; they will run and not grow weary, they will walk and not faint.",
    themes: ["exhaustion", "waiting", "discouragement"],
  },
  {
    reference: "Galatians 6:9",
    text: "Let us not grow weary in well-doing, for in due time we will reap a harvest if we do not give up.",
    themes: ["discouragement", "caring-for-others", "perseverance"],
  },
  {
    reference: "Psalm 34:18",
    text: "The LORD is near to the brokenhearted; He saves the contrite in spirit.",
    themes: ["grief", "loneliness", "despair"],
  },
  {
    reference: "Psalm 147:3",
    text: "He heals the brokenhearted and binds up their wounds.",
    themes: ["grief", "hurt"],
  },
  {
    reference: "Matthew 5:4",
    text: "Blessed are those who mourn, for they will be comforted.",
    themes: ["grief"],
  },
  {
    reference: "2 Corinthians 1:3-4",
    text: "Blessed be the God and Father of our Lord Jesus Christ, the Father of compassion and the God of all comfort, who comforts us in all our troubles, so that we can comfort those in any trouble with the comfort we ourselves have received from God.",
    themes: ["grief", "comfort"],
  },
  {
    reference: "Romans 8:1",
    text: "Therefore, there is now no condemnation for those who are in Christ Jesus.",
    themes: ["shame", "guilt", "failure"],
  },
  {
    reference: "Psalm 103:12",
    text: "As far as the east is from the west, so far has He removed our transgressions from us.",
    themes: ["shame", "guilt", "forgiveness"],
  },
  {
    reference: "1 John 1:9",
    text: "If we confess our sins, He is faithful and just to forgive us our sins and to cleanse us from all unrighteousness.",
    themes: ["guilt", "forgiveness"],
  },
  {
    reference: "Isaiah 43:25",
    text: "I, yes I, am He who blots out your transgressions for My own sake and remembers your sins no more.",
    themes: ["shame", "guilt"],
  },
  {
    reference: "Psalm 139:13-14",
    text: "For You formed my inmost being; You knit me together in my mother’s womb. I praise You, for I am fearfully and wonderfully made. Marvelous are Your works, and I know this very well.",
    themes: ["identity", "worth", "comparison"],
  },
  {
    reference: "Ephesians 2:10",
    text: "For we are God’s workmanship, created in Christ Jesus to do good works, which God prepared in advance as our way of life.",
    themes: ["identity", "calling", "worth"],
  },
  {
    reference: "Isaiah 43:1-2",
    text: "Now this is what the LORD says— He who created you, O Jacob, and He who formed you, O Israel: Do not fear, for I have redeemed you; I have called you by your name; you are Mine! When you pass through the waters, I will be with you; and when you go through the rivers, they will not overwhelm you. When you walk through the fire, you will not be scorched; the flames will not set you ablaze.",
    themes: ["identity", "fear"],
  },
  {
    reference: "1 Peter 2:9",
    text: "But you are a chosen people, a royal priesthood, a holy nation, a people for God’s own possession, to proclaim the virtues of Him who called you out of darkness into His marvelous light.",
    themes: ["identity", "worth"],
  },
  {
    reference: "Psalm 27:14",
    text: "Wait patiently for the LORD; be strong and courageous. Wait patiently for the LORD!",
    themes: ["waiting", "uncertainty"],
  },
  {
    reference: "Lamentations 3:25-26",
    text: "The LORD is good to those who wait for Him, to the soul who seeks Him. It is good to wait quietly for the salvation of the LORD.",
    themes: ["waiting", "hope"],
  },
  {
    reference: "Habakkuk 2:3",
    text: "For the vision awaits an appointed time; it testifies of the end and does not lie. Though it lingers, wait for it, since it will surely come and will not delay.",
    themes: ["waiting", "calling"],
  },
  {
    reference: "Proverbs 3:5-6",
    text: "Trust in the LORD with all your heart, and lean not on your own understanding; in all your ways acknowledge Him, and He will make your paths straight.",
    themes: ["decisions", "calling", "uncertainty"],
  },
  {
    reference: "Jeremiah 29:11",
    text: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, to give you a future and a hope.",
    themes: ["calling", "uncertainty", "hope"],
  },
  {
    reference: "Psalm 32:8",
    text: "I will instruct you and teach you the way you should go; I will give you counsel and watch over you.",
    themes: ["decisions", "calling", "transition"],
  },
  {
    reference: "Micah 6:8",
    text: "He has shown you, O man, what is good. And what does the LORD require of you but to act justly, to love mercy, and to walk humbly with your God?",
    themes: ["calling", "purpose"],
  },
  {
    reference: "James 1:5",
    text: "Now if any of you lacks wisdom, he should ask God, who gives generously to all without finding fault, and it will be given to him.",
    themes: ["decisions", "wisdom"],
  },
  {
    reference: "Proverbs 16:9",
    text: "A man’s heart plans his course, but the LORD determines his steps.",
    themes: ["decisions", "calling"],
  },
  {
    reference: "Psalm 139:7-10",
    text: "Where can I go to escape Your Spirit? Where can I flee from Your presence? If I ascend to the heavens, You are there; if I make my bed in Sheol, You are there. If I rise on the wings of the dawn, if I settle by the farthest sea, even there Your hand will guide me; Your right hand will hold me fast.",
    themes: ["loneliness", "distance-from-God"],
  },
  {
    reference: "Deuteronomy 31:6",
    text: "Be strong and courageous; do not be afraid or terrified of them, for it is the LORD your God who goes with you; He will never leave you nor forsake you.",
    themes: ["loneliness", "fear", "transition"],
  },
  {
    reference: "Genesis 16:13",
    text: "So Hagar gave this name to the LORD who had spoken to her: “You are the God who sees me,” for she said, “Here I have seen the One who sees me!”",
    themes: ["loneliness", "feeling-unseen"],
  },
  {
    reference: "Hebrews 13:5",
    text: "Keep your lives free from the love of money and be content with what you have, for God has said: “Never will I leave you, never will I forsake you.”",
    themes: ["loneliness", "provision"],
  },
  {
    reference: "Ephesians 4:26-27",
    text: "“Be angry, yet do not sin.” Do not let the sun set upon your anger, and do not give the devil a foothold.",
    themes: ["anger", "resentment"],
  },
  {
    reference: "James 1:19-20",
    text: "My beloved brothers, understand this: Everyone should be quick to listen, slow to speak, and slow to anger, for man’s anger does not bring about the righteousness that God desires.",
    themes: ["anger", "relationships"],
  },
  {
    reference: "Ephesians 4:31-32",
    text: "Get rid of all bitterness, rage and anger, outcry and slander, along with every form of malice. Be kind and tenderhearted to one another, forgiving each other just as in Christ God forgave you.",
    themes: ["anger", "resentment", "forgiveness"],
  },
  {
    reference: "Galatians 6:4-5",
    text: "Each one should test his own work. Then he will have reason to boast in himself alone, and not in someone else. For each one should carry his own load.",
    themes: ["comparison", "boundaries", "people-pleasing"],
  },
  {
    reference: "Proverbs 14:30",
    text: "A tranquil heart is life to the body, but envy rots the bones.",
    themes: ["comparison", "envy"],
  },
  {
    reference: "Matthew 6:31-33",
    text: "Therefore do not worry, saying, ‘What shall we eat?’ or ‘What shall we drink?’ or ‘What shall we wear?’ For the Gentiles strive after all these things, and your heavenly Father knows that you need them. But seek first the kingdom of God and His righteousness, and all these things will be added unto you.",
    themes: ["provision", "anxiety"],
  },
  {
    reference: "Philippians 4:19",
    text: "And my God will supply all your needs according to His glorious riches in Christ Jesus.",
    themes: ["provision"],
  },
  {
    reference: "Psalm 23:1-3",
    text: "The LORD is my shepherd; I shall not want. He makes me lie down in green pastures; He leads me beside quiet waters. He restores my soul; He guides me in the paths of righteousness for the sake of His name.",
    themes: ["provision", "rest", "exhaustion"],
  },
  {
    reference: "Colossians 3:13",
    text: "Bear with one another and forgive any complaint you may have against someone else. Forgive as the Lord forgave you.",
    themes: ["forgiveness", "relationships"],
  },
  {
    reference: "Romans 12:18",
    text: "If it is possible on your part, live at peace with everyone.",
    themes: ["relationships", "conflict"],
  },
  {
    reference: "Proverbs 15:1",
    text: "A gentle answer turns away wrath, but a harsh word stirs up anger.",
    themes: ["relationships", "conflict", "anger"],
  },
  {
    reference: "1 Corinthians 13:4-5",
    text: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It is not rude, it is not self-seeking, it is not easily angered, it keeps no account of wrongs.",
    themes: ["relationships", "love"],
  },
  {
    reference: "Isaiah 40:11",
    text: "He tends His flock like a shepherd; He gathers the lambs in His arms and carries them close to His heart. He gently leads the nursing ewes.",
    themes: ["caring-for-others", "motherhood", "comfort"],
  },
  {
    reference: "1 Peter 4:10",
    text: "As good stewards of the manifold grace of God, each of you should use whatever gift he has received to serve one another.",
    themes: ["caring-for-others", "calling"],
  },
  {
    reference: "2 Corinthians 12:9",
    text: "But He said to me, “My grace is sufficient for you, for My power is perfected in weakness.” Therefore I will boast all the more gladly in my weaknesses, so that the power of Christ may rest on me.",
    themes: ["illness", "weakness", "failure"],
  },
  {
    reference: "Psalm 73:26",
    text: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.",
    themes: ["illness", "exhaustion", "weakness"],
  },
  {
    reference: "Romans 8:18",
    text: "I consider that our present sufferings are not comparable to the glory that will be revealed in us.",
    themes: ["illness", "suffering", "hope"],
  },
  {
    reference: "Joshua 1:9",
    text: "Have I not commanded you to be strong and courageous? Do not be afraid; do not be discouraged, for the LORD your God is with you wherever you go.",
    themes: ["fear", "transition", "discouragement"],
  },
  {
    reference: "2 Corinthians 4:16-18",
    text: "Therefore we do not lose heart. Though our outer self is wasting away, yet our inner self is being renewed day by day. For our light and momentary affliction is producing for us an eternal glory that is far beyond comparison. So we fix our eyes not on what is seen, but on what is unseen. For what is seen is temporary, but what is unseen is eternal.",
    themes: ["discouragement", "suffering", "perseverance"],
  },
  {
    reference: "Romans 5:3-5",
    text: "Not only that, but we also rejoice in our sufferings, because we know that suffering produces perseverance; perseverance, character; and character, hope. And hope does not disappoint us, because God has poured out His love into our hearts through the Holy Spirit, whom He has given us.",
    themes: ["perseverance", "suffering", "hope"],
  },
  {
    reference: "Psalm 46:10",
    text: "“Be still and know that I am God; I will be exalted among the nations, I will be exalted over the earth.”",
    themes: ["rest", "stillness", "overwhelm"],
  },
  {
    reference: "Exodus 33:14",
    text: "And the LORD answered, “My Presence will go with you, and I will give you rest.”",
    themes: ["rest", "transition"],
  },
  {
    reference: "Mark 6:31",
    text: "And He said to them, “Come with Me privately to a solitary place, and let us rest for a while.” For many people were coming and going, and they did not even have time to eat.",
    themes: ["rest", "exhaustion", "boundaries"],
  },
  {
    reference: "Lamentations 3:22-23",
    text: "Because of the loving devotion of the LORD we are not consumed, for His mercies never fail. They are new every morning; great is Your faithfulness!",
    themes: ["hope", "renewal", "despair"],
  },
  {
    reference: "Romans 15:13",
    text: "Now may the God of hope fill you with all joy and peace as you believe in Him, so that you may overflow with hope by the power of the Holy Spirit.",
    themes: ["hope", "renewal"],
  },
  {
    reference: "Isaiah 43:18-19",
    text: "Do not call to mind the former things; pay no attention to the things of old. Behold, I am about to do something new; even now it is coming. Do you not see it? Indeed, I will make a way in the wilderness and streams in the desert.",
    themes: ["renewal", "transition", "hope"],
  },
  {
    reference: "2 Corinthians 5:17",
    text: "Therefore if anyone is in Christ, he is a new creation. The old has passed away. Behold, the new has come!",
    themes: ["renewal", "identity"],
  },
  {
    reference: "Ecclesiastes 3:1",
    text: "To everything there is a season, and a time for every purpose under heaven:",
    themes: ["transition", "seasons"],
  },
  {
    reference: "Galatians 1:10",
    text: "Am I now seeking the approval of men, or of God? Or am I striving to please men? If I were still trying to please men, I would not be a servant of Christ.",
    themes: ["people-pleasing", "boundaries"],
  },
  {
    reference: "Proverbs 29:25",
    text: "The fear of man is a snare, but whoever trusts in the LORD is set securely on high.",
    themes: ["people-pleasing", "fear"],
  },
  {
    reference: "Psalm 127:1-2",
    text: "Unless the LORD builds the house, its builders labor in vain; unless the LORD protects the city, its watchmen stand guard in vain. In vain you rise early and stay up late, toiling for bread to eat— for He gives sleep to His beloved.",
    themes: ["boundaries", "exhaustion", "striving"],
  },
  {
    reference: "Psalm 42:11",
    text: "Why are you downcast, O my soul? Why the unease within me? Put your hope in God, for I will yet praise Him, my Savior and my God.",
    themes: ["despair", "distance-from-God", "hope"],
  },
  {
    reference: "Mark 9:24",
    text: "Immediately the boy’s father cried out, “I do believe; help my unbelief!”",
    themes: ["doubt", "distance-from-God"],
  },
  {
    reference: "James 4:8",
    text: "Draw near to God, and He will draw near to you. Cleanse your hands, you sinners, and purify your hearts, you double-minded.",
    themes: ["distance-from-God"],
  },
  {
    reference: "Psalm 13:1-2",
    text: "How long, O LORD? Will You forget me forever? How long will You hide Your face from me? How long must I wrestle in my soul, with sorrow in my heart each day? How long will my enemy dominate me?",
    themes: ["despair", "distance-from-God", "waiting"],
  },
];

const BY_REFERENCE = new Map(SCRIPTURE_LIBRARY.map((p) => [p.reference, p]));

/**
 * Resolves what the model chose to verified text. Returns null for anything
 * not in the library, which is how an invented reference gets dropped rather
 * than published.
 */
export function findPassage(reference: string | null | undefined): ScripturePassage | null {
  if (!reference) return null;
  return BY_REFERENCE.get(reference.trim()) ?? null;
}

/** The catalogue the model chooses from, rendered into the system prompt. */
export function scriptureCatalogue(): string {
  return SCRIPTURE_LIBRARY.map(
    (p) => `${p.reference} [${p.themes.join(", ")}] ${p.text}`,
  ).join("\n");
}

