// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/thirty-one-rooted-current/Current.tsx": () => import("../components/mockups/thirty-one-rooted-current/Current.tsx")
};
