#!/usr/bin/env node
/**
 * Refreshes the self-hosted webfonts under public/fonts and regenerates
 * src/fonts.css.
 *
 * We serve Cormorant Garamond and DM Sans from our own origin rather than
 * linking fonts.googleapis.com. Two reasons: no visitor IP is handed to a third
 * party on page load (this is a UK site, so UK GDPR applies), and the fonts stop
 * being a cross-origin hop on the critical path.
 *
 * Only the weights the site actually uses are fetched. Cormorant is used at 300
 * for h1/h2 and at 400 for pull quotes and serif inputs, each with an italic;
 * DM Sans is variable, so one file per style covers 100-1000. Subsets are
 * limited to latin and latin-ext. If a design change introduces a new weight,
 * add it to FAMILIES below and re-run:
 *
 *   node scripts/fetch-fonts.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const FONT_DIR = path.join(ROOT, "public", "fonts");
const CSS_FILE = path.join(ROOT, "src", "fonts.css");

const FAMILIES = [
  "Cormorant+Garamond:ital,wght@0,300;0,400;1,300;1,400",
  "DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000",
];
const SUBSETS = new Set(["latin", "latin-ext"]);

// Google serves woff2 only to browsers that advertise support.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36";

const cssUrl =
  "https://fonts.googleapis.com/css2?" +
  FAMILIES.map((family) => `family=${family}`).join("&") +
  "&display=swap";

const source = execFileSync("curl", ["-sS", "-fL", "-H", `User-Agent: ${UA}`, cssUrl], {
  encoding: "utf8",
});

fs.rmSync(FONT_DIR, { recursive: true, force: true });
fs.mkdirSync(FONT_DIR, { recursive: true });

const faces = [];
for (const [, subset, face] of source.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
  if (!SUBSETS.has(subset)) continue;

  const family = /font-family:\s*'([^']+)'/.exec(face)[1];
  const style = /font-style:\s*(\w+)/.exec(face)[1];
  const weight = /font-weight:\s*([\d ]+)/.exec(face)[1].trim();
  const url = /url\((https:[^)]+)\)/.exec(face)[1];

  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const file = `${slug}-${weight.replace(/\s+/g, "-")}-${style}-${subset}.woff2`;

  execFileSync("curl", ["-sS", "-fL", url, "-o", path.join(FONT_DIR, file)]);
  faces.push(face.replace(/url\(https:[^)]+\)/, `url('/fonts/${file}')`));
}

if (faces.length === 0) {
  throw new Error("No matching @font-face blocks were returned by Google Fonts.");
}

const header = `/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.

   Cormorant Garamond and DM Sans, latin and latin-ext subsets, served from this
   origin instead of fonts.gstatic.com so that no visitor IP reaches a third
   party. Re-run the script to change weights or subsets. */\n\n`;

fs.writeFileSync(CSS_FILE, header + faces.join("\n\n") + "\n");
console.log(`Fetched ${faces.length} faces into ${path.relative(ROOT, FONT_DIR)}.`);
